language: php

matrix:
  include:
    - php: 7.1
      env:
        - ENABLE_XDEBUG=true
  fast_finish: true

os:
  - linux

sudo: false

cache:
  directories:
    - vendor/

before_script:
  - export PATH="$PATH:$HOME/.composer/vendor/bin"
  - phpenv config-add custom.ini
  - if [[ ! $ENABLE_XDEBUG ]]; then
      phpenv config-rm xdebug.ini || echo "ext-xdebug is not available, cannot remove it.";
    fi

script:
  - php -i | grep 'intl'
  - ls -lh /home/travis/.phpenv/versions/7.1.11/lib/php/extensions/no-debug-zts-20160303/
  - composer install
#  - vendor/bin/hoa test:run
#  - if [[ $ENABLE_DEVTOOLS ]]; then
#      composer global require friendsofphp/php-cs-fixer;
#      vendor/bin/hoa devtools:cs --diff --dry-run .;
#    fi

addons:
  apt:
    packages:
    - libicu-dev
    - unicode
    - unicode-data
    - ttf-ancient-fonts
    - xfonts-efont-unicode
    - unifont
    - ttf-unifont
    - locales
    - language-pack-en
    - language-pack-fr
