language: php

matrix:
  include:
    - php: 7.1
      env:
        - ENABLE_XDEBUG=true
  fast_finish: true

os:
  - linux

sudo: false

before_script:
  - export PATH="$PATH:$HOME/.composer/vendor/bin"
  - if [[ ! $ENABLE_XDEBUG ]]; then
      phpenv config-rm xdebug.ini || echo "ext-xdebug is not available, cannot remove it.";
    fi

script:
  - ls -lha
  - composer install
  - vendor/bin/hoa test:run

addons:
  apt:
    packages:
    - libicu-dev
    - unicode
    - unicode-data
    - ttf-ancient-fonts
    - xfonts-efont-unicode
    - unifont
    - ttf-unifont
    - locales
    - language-pack-en
    - language-pack-fr
    - tree
