language: php

matrix:
  include:
    - php: 7.1
      env:
        - ENABLE_XDEBUG=true
  fast_finish: true

os:
  - linux

sudo: false

before_script:
  - export PATH="$PATH:$HOME/.composer/vendor/bin"
  - if [[ ! $ENABLE_XDEBUG ]]; then
      phpenv config-rm xdebug.ini || echo "ext-xdebug is not available, cannot remove it.";
    fi
  - echo $TRAVIS_PHP_VERSION
  - curl -Ss http://ie1.php.net/distributions/php-$TRAVIS_PHP_VERSION.tar.bz2 -o /home/travis/php-src.tar.bz2 && cd /home/travis/ && mkdir php-src && tar xjf php-src.tar.bz2 -C php-src --strip-components=1 && cd php-src/ext/intl && phpize && ./configure && make && make install
  - cd $TRAVIS_BUILD_DIR

script:
  - composer install
  - vendor/bin/hoa test:run

addons:
  apt:
    packages:
    - libicu-dev
    - unicode
    - unicode-data
    - ttf-ancient-fonts
    - xfonts-efont-unicode
    - unifont
    - ttf-unifont
    - locales
    - language-pack-en
