language: php

matrix:
  include:
    - php: 7.1
      env:
        - ENABLE_XDEBUG=true
  fast_finish: true

os:
  - linux

sudo: false

before_script:
  - export PATH="$PATH:$HOME/.composer/vendor/bin"
  - phpenv config-add custom.ini
  - if [[ ! $ENABLE_XDEBUG ]]; then
      phpenv config-rm xdebug.ini || echo "ext-xdebug is not available, cannot remove it.";
    fi
  - curl -Ss http://ie1.php.net/distributions/php-7.1.11.tar.bz2 -o /home/travis/php-src.tar.bz2 && cd /home/travis/ && mkdir php-src && tar xjf php-src.tar.bz2 -C php-src --strip-components=1 && cd php-src/ext/intl && phpize && ./configure && make && make install
  - grep -Rni 'intl.so' /home/travis/.phpenv/versions/7.1.11/
  - php -i | grep 'intl'
  - tree /home/travis/.phpenv/versions/7.1.11/lib/php/extensions


script:
  - composer install
  - vendor/bin/hoa test:run

addons:
  apt:
    packages:
    - libicu-dev
    - unicode
    - unicode-data
    - ttf-ancient-fonts
    - xfonts-efont-unicode
    - unifont
    - ttf-unifont
    - locales
    - language-pack-en
    - language-pack-fr
    - tree
