language: php

matrix:
  include:
    - php: 7.0
      env:
        - ENABLE_XDEBUG=true
  fast_finish: true

os:
  - linux

sudo: false

before_script:
  - export PATH="$PATH:$HOME/.composer/vendor/bin"
  - if [[ ! $ENABLE_XDEBUG ]]; then
      phpenv config-rm xdebug.ini || echo "ext-xdebug is not available, cannot remove it.";
    fi

script:
  - ls -lha
  - composer install
  - vendor/bin/hoa test:run

